/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EssayRouteImport } from './routes/essay'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BlankRouteImport } from './routes/blank'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnlockIndexRouteImport } from './routes/unlock.index'
import { Route as UnlockSuccessRouteImport } from './routes/unlock.success'
import { Route as UnlockCancelRouteImport } from './routes/unlock.cancel'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayRoute = EssayRouteImport.update({
  id: '/essay',
  path: '/essay',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankRoute = BlankRouteImport.update({
  id: '/blank',
  path: '/blank',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockIndexRoute = UnlockIndexRouteImport.update({
  id: '/unlock/',
  path: '/unlock/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockSuccessRoute = UnlockSuccessRouteImport.update({
  id: '/unlock/success',
  path: '/unlock/success',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockCancelRoute = UnlockCancelRouteImport.update({
  id: '/unlock/cancel',
  path: '/unlock/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blank': typeof BlankRoute
  '/dashboard': typeof DashboardRoute
  '/essay': typeof EssayRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/unlock/cancel': typeof UnlockCancelRoute
  '/unlock/success': typeof UnlockSuccessRoute
  '/unlock/': typeof UnlockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blank': typeof BlankRoute
  '/dashboard': typeof DashboardRoute
  '/essay': typeof EssayRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/unlock/cancel': typeof UnlockCancelRoute
  '/unlock/success': typeof UnlockSuccessRoute
  '/unlock': typeof UnlockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blank': typeof BlankRoute
  '/dashboard': typeof DashboardRoute
  '/essay': typeof EssayRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/unlock/cancel': typeof UnlockCancelRoute
  '/unlock/success': typeof UnlockSuccessRoute
  '/unlock/': typeof UnlockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blank'
    | '/dashboard'
    | '/essay'
    | '/onboarding'
    | '/profile'
    | '/signin'
    | '/unlock/cancel'
    | '/unlock/success'
    | '/unlock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blank'
    | '/dashboard'
    | '/essay'
    | '/onboarding'
    | '/profile'
    | '/signin'
    | '/unlock/cancel'
    | '/unlock/success'
    | '/unlock'
  id:
    | '__root__'
    | '/'
    | '/blank'
    | '/dashboard'
    | '/essay'
    | '/onboarding'
    | '/profile'
    | '/signin'
    | '/unlock/cancel'
    | '/unlock/success'
    | '/unlock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlankRoute: typeof BlankRoute
  DashboardRoute: typeof DashboardRoute
  EssayRoute: typeof EssayRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  UnlockCancelRoute: typeof UnlockCancelRoute
  UnlockSuccessRoute: typeof UnlockSuccessRoute
  UnlockIndexRoute: typeof UnlockIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay': {
      id: '/essay'
      path: '/essay'
      fullPath: '/essay'
      preLoaderRoute: typeof EssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank': {
      id: '/blank'
      path: '/blank'
      fullPath: '/blank'
      preLoaderRoute: typeof BlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock/': {
      id: '/unlock/'
      path: '/unlock'
      fullPath: '/unlock/'
      preLoaderRoute: typeof UnlockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock/success': {
      id: '/unlock/success'
      path: '/unlock/success'
      fullPath: '/unlock/success'
      preLoaderRoute: typeof UnlockSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock/cancel': {
      id: '/unlock/cancel'
      path: '/unlock/cancel'
      fullPath: '/unlock/cancel'
      preLoaderRoute: typeof UnlockCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlankRoute: BlankRoute,
  DashboardRoute: DashboardRoute,
  EssayRoute: EssayRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  UnlockCancelRoute: UnlockCancelRoute,
  UnlockSuccessRoute: UnlockSuccessRoute,
  UnlockIndexRoute: UnlockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
