/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as TosRouteImport } from './routes/tos'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EssayRouteImport } from './routes/essay'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BlankRouteImport } from './routes/blank'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnlockIndexRouteImport } from './routes/unlock.index'
import { Route as UnlockSuccessRouteImport } from './routes/unlock.success'
import { Route as UnlockCancelRouteImport } from './routes/unlock.cancel'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as ApplicationSystemExternalIdRouteImport } from './routes/application.$system.$externalId'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayRoute = EssayRouteImport.update({
  id: '/essay',
  path: '/essay',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankRoute = BlankRouteImport.update({
  id: '/blank',
  path: '/blank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockIndexRoute = UnlockIndexRouteImport.update({
  id: '/unlock/',
  path: '/unlock/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockSuccessRoute = UnlockSuccessRouteImport.update({
  id: '/unlock/success',
  path: '/unlock/success',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockCancelRoute = UnlockCancelRouteImport.update({
  id: '/unlock/cancel',
  path: '/unlock/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplicationSystemExternalIdRoute =
  ApplicationSystemExternalIdRouteImport.update({
    id: '/application/$system/$externalId',
    path: '/application/$system/$externalId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/blank': typeof BlankRoute
  '/dashboard': typeof DashboardRoute
  '/essay': typeof EssayRoute
  '/onboarding': typeof OnboardingRoute
  '/prep': typeof PrepRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/tos': typeof TosRoute
  '/universities': typeof UniversitiesRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/unlock/cancel': typeof UnlockCancelRoute
  '/unlock/success': typeof UnlockSuccessRoute
  '/unlock/': typeof UnlockIndexRoute
  '/application/$system/$externalId': typeof ApplicationSystemExternalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/blank': typeof BlankRoute
  '/dashboard': typeof DashboardRoute
  '/essay': typeof EssayRoute
  '/onboarding': typeof OnboardingRoute
  '/prep': typeof PrepRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/tos': typeof TosRoute
  '/universities': typeof UniversitiesRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/unlock/cancel': typeof UnlockCancelRoute
  '/unlock/success': typeof UnlockSuccessRoute
  '/unlock': typeof UnlockIndexRoute
  '/application/$system/$externalId': typeof ApplicationSystemExternalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/blank': typeof BlankRoute
  '/dashboard': typeof DashboardRoute
  '/essay': typeof EssayRoute
  '/onboarding': typeof OnboardingRoute
  '/prep': typeof PrepRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/tos': typeof TosRoute
  '/universities': typeof UniversitiesRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/unlock/cancel': typeof UnlockCancelRoute
  '/unlock/success': typeof UnlockSuccessRoute
  '/unlock/': typeof UnlockIndexRoute
  '/application/$system/$externalId': typeof ApplicationSystemExternalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/blank'
    | '/dashboard'
    | '/essay'
    | '/onboarding'
    | '/prep'
    | '/profile'
    | '/signin'
    | '/tos'
    | '/universities'
    | '/apply/$jobId'
    | '/oauth/callback'
    | '/unlock/cancel'
    | '/unlock/success'
    | '/unlock/'
    | '/application/$system/$externalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/blank'
    | '/dashboard'
    | '/essay'
    | '/onboarding'
    | '/prep'
    | '/profile'
    | '/signin'
    | '/tos'
    | '/universities'
    | '/apply/$jobId'
    | '/oauth/callback'
    | '/unlock/cancel'
    | '/unlock/success'
    | '/unlock'
    | '/application/$system/$externalId'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/blank'
    | '/dashboard'
    | '/essay'
    | '/onboarding'
    | '/prep'
    | '/profile'
    | '/signin'
    | '/tos'
    | '/universities'
    | '/apply/$jobId'
    | '/oauth/callback'
    | '/unlock/cancel'
    | '/unlock/success'
    | '/unlock/'
    | '/application/$system/$externalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  BlankRoute: typeof BlankRoute
  DashboardRoute: typeof DashboardRoute
  EssayRoute: typeof EssayRoute
  OnboardingRoute: typeof OnboardingRoute
  PrepRoute: typeof PrepRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  TosRoute: typeof TosRoute
  UniversitiesRoute: typeof UniversitiesRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  UnlockCancelRoute: typeof UnlockCancelRoute
  UnlockSuccessRoute: typeof UnlockSuccessRoute
  UnlockIndexRoute: typeof UnlockIndexRoute
  ApplicationSystemExternalIdRoute: typeof ApplicationSystemExternalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay': {
      id: '/essay'
      path: '/essay'
      fullPath: '/essay'
      preLoaderRoute: typeof EssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank': {
      id: '/blank'
      path: '/blank'
      fullPath: '/blank'
      preLoaderRoute: typeof BlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock/': {
      id: '/unlock/'
      path: '/unlock'
      fullPath: '/unlock/'
      preLoaderRoute: typeof UnlockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock/success': {
      id: '/unlock/success'
      path: '/unlock/success'
      fullPath: '/unlock/success'
      preLoaderRoute: typeof UnlockSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock/cancel': {
      id: '/unlock/cancel'
      path: '/unlock/cancel'
      fullPath: '/unlock/cancel'
      preLoaderRoute: typeof UnlockCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/application/$system/$externalId': {
      id: '/application/$system/$externalId'
      path: '/application/$system/$externalId'
      fullPath: '/application/$system/$externalId'
      preLoaderRoute: typeof ApplicationSystemExternalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApplyRouteChildren {
  ApplyJobIdRoute: typeof ApplyJobIdRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyJobIdRoute: ApplyJobIdRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRouteWithChildren,
  BlankRoute: BlankRoute,
  DashboardRoute: DashboardRoute,
  EssayRoute: EssayRoute,
  OnboardingRoute: OnboardingRoute,
  PrepRoute: PrepRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  TosRoute: TosRoute,
  UniversitiesRoute: UniversitiesRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  UnlockCancelRoute: UnlockCancelRoute,
  UnlockSuccessRoute: UnlockSuccessRoute,
  UnlockIndexRoute: UnlockIndexRoute,
  ApplicationSystemExternalIdRoute: ApplicationSystemExternalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
